### ISSUE TITLE
Hello world not displaying

### ISSUE THREAD

**Issue by eveenendaal** [yewstack/yew-trunk-minimal-template#11]
```
cargo generate --git https://github.com/yewstack/yew-trunk-minimal-template
# named it hello
cd hello
rustup target add wasm32-unknown-unknown
cargo install trunk wasm-bindgen-cli
trunk serve
```

I ran the following commands on my m1 mac, and after updating the cargo.lock file to use "0.2.87" instead of "0.2.83" in a few places so the code would actually start, this is what I get when I go to "[127.0.0.1:](http://127.0.0.1:8080)"

<img width="1950" alt="Screenshot 2023-07-09 at 15 40 39" src="https://github.com/yewstack/yew-trunk-minimal-template/assets/71555/73a9efc3-5f96-4139-8a46-cc9c04dcd9d0">

**Comment by futursolo** [comment]
This has been fixed in #12.
